name: Build Extension
on: [push, pull_request]

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.16.1
      - name: Restore lerna cache
        id: lerna-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: lucasmotta/pull-request-sticky-header@1.0.0
        with:
          header: '> [Download the latest builds](https://github.com/blockstack/ux/actions/runs/${{ github.run_id }}).'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install monorepo deps
        run: yarn --frozen-lockfile
        if: steps.lerna-cache.outputs.cache-hit != 'true'
      - name: Build extension
        run: sh build-ext.sh
      - uses: actions/upload-artifact@v2
        name: Upload Extension Zip
        with:
          name: connect-extension
          path: connect-extension.zip
      - name: Sign Production Firefox version
        if: github.ref == 'refs/heads/master'
        run: yarn web-ext sign --channel=listed
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - name: Sign Firefox extension
        if: github.ref != 'refs/heads/master'
        run: yarn web-ext sign --channel=unlisted
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - uses: actions/upload-artifact@v2
        name: Upload Firefox Add-On XPI
        with:
          name: connect-addon
          path: web-ext-artifacts/*.xpi
