name: Git Tag
on:
  push:
    branches:
      - 'main'
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  git_tag:
    name: Create git tag
    runs-on: ubuntu-latest
    if: github.event.head_commit.message == 'Version release'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get tag version
        id: release_info
        run: |
          version="$(cat package.json | jq -r '.version')"
          release_body="$(sed -n "/## ${version}/,/## [0-9]/p" CHANGELOG.md | sed \$d| sed 's/##/#/g')"

          echo "::set-output name=version::${version}"
          echo "::set-output name=release_body::${release_body}"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.release_info.outputs.release_body }}
          commit: ${{ github.sha }}
          tag: v${{ steps.release_info.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
