name: UX
on: [push]

jobs:
  test_keychain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Node Version
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.16.1
    - name: Restore lerna cache
      id: lerna-cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install monorepo deps
      run: yarn --frozen-lockfile
      if: steps.lerna-cache.outputs.cache-hit != 'true'
    - name: Keychain tests
      run: yarn lerna run test --scope @blockstack/keychain

  codecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Node Version
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.16.1
    - name: Restore lerna cache
      id: lerna-cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install monorepo deps
      run: yarn --frozen-lockfile
      if: steps.lerna-cache.outputs.cache-hit != 'true'
    - name: Lint
      run: yarn lint
    - name: Typecheck
      run: yarn typecheck

  publish:
    needs: [test_keychain, codecheck]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout master
      run: git checkout master
    - name: Set Node Version
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.16.1
    - name: Install monorepo deps (no cache)
      run: yarn --frozen-lockfile
      if: steps.lerna-cache.outputs.cache-hit != 'true'
    - name: Setup .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - name: Setup git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Lerna Version
      run: yarn lerna version --conventional-commits --no-push --yes
    - name: Publish
      run: yarn lerna publish from-git --conventional-commits --yes
    - name: Push changes
      uses: ad-m/github-push-action@fe38f0a
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
